export const data = [
    [0,  "corner",       "",            "",                       "GO",                       "",         0],
    [1,  "property",     "brown",       "",                       "Mediterranean",            "$60",      60],
    [2,  "luck",         "",            "toolbox",                "Community Chest",          "",         0],
    [3,  "property",     "brown",       "",                       "Baltic Avenue",            "$60",      60],
    [4,  "icon",         "",            "money-check-dollar",     "Tax Income",               "$200",     200],
    [5,  "icon",         "",            "train",                  "Reading Railroad",         "$200",     200],
    [6,  "property",     "skyblue",     "",                       "Oriental Avenue",          "$100",     100],
    [7,  "luck",         "",            "question",               "Chance",                   "",         0],
    [8,  "property",     "skyblue",     "",                       "Vermont Avenue",           "$100",     100],
    [9,  "property",     "skyblue",     "",                       "Connecticut",              "$120",     120],
    [10, "corner",       "",            "",                       "Just Visiting",            "",         0],
    [11, "property",     "magenta",     "",                       "St. Charles Place",        "$140",     140],
    [12, "icon",         "",            "lightbulb",              "Electric Company",         "$150",     150],
    [13, "property",     "magenta",     "",                       "States Avenue",            "$140",     140],
    [14, "property",     "magenta",     "",                       "Virginia Avenue",          "$160",     160],
    [15, "icon",         "",            "train",                  "Pennsylvania Railroad",    "$200",     200],
    [16, "property",     "orange",      "",                       "St. James Place",          "$180",     180],
    [17, "luck",         "",            "toolbox",                "Community Chest",          "",         0],
    [18, "property",     "orange",      "",                       "Tennessee Avenue",         "$180",     180],
    [19, "property",     "orange",      "",                       "New York Avenue",          "$200",     200],
    [20, "corner",       "",            "",                       "Free Parking",             "",         0],
    [21, "property",     "red",         "",                       "Kentucky Avenue",          "$220",     220],
    [22, "luck",         "",            "question",               "Chance",                   "",         0],
    [23, "property",     "red",         "",                       "Indiana Avenue",           "$220",     220],
    [24, "property",     "red",         "",                       "Illinois Avenue",          "$240",     240],
    [25, "icon",         "",            "train",                  "B. & O. Railroad",         "$200",     200],
    [26, "property",     "yellow",      "",                       "Atletic Avenue",           "$260",     260],
    [27, "property",     "yellow",      "",                       "Ventnor Avenue",           "$260",     260],
    [28, "icon",         "",            "faucet-drip",            "Water Works",              "$150",     150],
    [29, "property",     "yellow",      "",                       "Marvin Gardens",           "$280",     280],
    [30, "corner",       "",            "",                       "Jail",                     "",         0],
    [31, "property",     "green",       "",                       "Pacific Avenue",           "$300",     300],
    [32, "property",     "green",       "",                       "North Carolina Avenue",    "$300",     300],
    [33, "luck",         "",            "toolbox",                "Community Chest",          "",         0],
    [34, "property",     "green",       "",                       "Pennsylvania Avenue",      "$320",     230],
    [35, "icon",         "",            "train",                  "Short Line",               "$200",     200],
    [36, "luck",         "",            "question",               "Chance",                   "",         0],
    [37, "property",     "blue",        "",                       "Park Place",               "$350",     350],
    [38, "icon",         "",            "handcuffs",              "Luxury Tax",               "$150",     150],
    [39, "property",     "blue",        "",                       "Boardwalk",                "$400",     400],
]